
export const MOONLIGHT_INCOME = [
  { id: "1", venue: "צוקר תל אביב", date: "2025-12-11", tickets: 300, amountPreVat: 24857, amountWithVat: 29331.26, expenses: 23753, expensesPaid: 23753, profit: 1104, receiver: "איתמר", invoice: "נכנס", hasCommission: false, commissionAmount: 0, paidToMusicians: true, amir: 276, itamar: 276, yuval: 276, guy: 276 },
  { id: "2", venue: "רחבת הבימה", date: "2025-12-18", tickets: 0, amountPreVat: 14000, amountWithVat: 16520, expenses: 3930, expensesPaid: 3930, profit: 10070, receiver: "איתמר", invoice: "נכנס", hasCommission: true, commissionAmount: 2014, paidToMusicians: true, amir: 3021, itamar: 3021, yuval: 2014, guy: 2014 },
  { id: "3", venue: "מיוזיק סיטי 2 (באר שבע)", date: "2025-12-25", tickets: 209, amountPreVat: 16276, amountWithVat: 19205.68, expenses: 14653, expensesPaid: 14653, profit: 1623, receiver: "איתמר", invoice: "נכנס", hasCommission: false, commissionAmount: 0, paidToMusicians: true, amir: 405.75, itamar: 405.75, yuval: 405.75, guy: 405.75 },
  { id: "4", venue: "ג'מס פתח תקווה", date: "2026-01-04", tickets: 198, amountPreVat: 11741.53, amountWithVat: 13855, expenses: 2168, expensesPaid: 2168, profit: 9573.53, receiver: "איתמר", invoice: "נכנס", hasCommission: true, commissionAmount: 1914.71, paidToMusicians: true, amir: 2872.06, itamar: 2872.06, yuval: 1914.71, guy: 1914.71 },
  { id: "5", venue: "זאפה חיפה", date: "2026-01-07", tickets: 336, amountPreVat: 22186.44, amountWithVat: 26180, expenses: 14065, expensesPaid: 14065, profit: 8121.44, receiver: "איתמר", invoice: "נכנס", hasCommission: true, commissionAmount: 1624.29, paidToMusicians: true, amir: 2436.43, itamar: 2436.43, yuval: 1624.29, guy: 1624.29 },
  { id: "6", venue: "זאפה הרצליה", date: "2026-05-07", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
  { id: "7", venue: "זאפה ירושלים", date: "2026-05-13", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
  { id: "8", venue: "זאפה הרצליה", date: "2026-05-27", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
  { id: "9", venue: "טרקלין פרדס חנה", date: "2026-06-16", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
  { id: "10", venue: "זאפה חיפה", date: "2026-06-17", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
  { id: "11", venue: "גריי מודיעין", date: "2026-06-22", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
  { id: "12", venue: "יד לבנים רעננה", date: "2026-07-16", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
  { id: "13", venue: "גריי תל אביב", date: "2026-08-12", tickets: 0, amountPreVat: 0, amountWithVat: 0, expenses: 0, expensesPaid: 0, profit: 0, receiver: "איתמר", invoice: null, hasCommission: false, commissionAmount: 0, paidToMusicians: false, amir: 0, itamar: 0, yuval: 0, guy: 0 },
];

export const MOONLIGHT_EVENT_EXPENSES = [
  { id: "1", event: "צוקר תל אביב - 11/12/2025", status: "נכנס", tickets: 300, campaign: 7400, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 653, akomPaid: true, hallFee: 9000, hallFeePaid: true, soundCompany: 0, soundCompanyPaid: true, bracelets: 2500, braceletsPaid: true, lightman: 1200, lightmanPaid: true, soundman: 1200, soundmanPaid: true, singer: 1800, singerPaid: true, vatSummary: 1107.54, totalPaid: 0 },
  { id: "2", event: "רחבת הבימה - 18/12/2025", status: "נכנס", tickets: 0, campaign: 0, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 0, akomPaid: true, hallFee: 0, hallFeePaid: true, soundCompany: 0, soundCompanyPaid: true, bracelets: 0, braceletsPaid: true, lightman: 1200, lightmanPaid: true, soundman: 1230, soundmanPaid: true, singer: 1500, singerPaid: true, vatSummary: 491.4, totalPaid: 0 },
  { id: "3", event: "מיוזיק סיטי 2 (באר שבע) - 25/12/2025", status: "נכנס", tickets: 209, campaign: 7200, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 653, akomPaid: true, hallFee: 0, hallFeePaid: true, soundCompany: 0, soundCompanyPaid: true, bracelets: 2900, braceletsPaid: true, lightman: 1200, lightmanPaid: true, soundman: 1200, soundmanPaid: true, singer: 1500, singerPaid: true, vatSummary: 1125.54, totalPaid: 0 },
  { id: "4", event: "ג'מס פתח תקווה - 04/01/2026", status: "נכנס", tickets: 198, campaign: 0, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 668, akomPaid: true, hallFee: 0, hallFeePaid: true, soundCompany: 0, soundCompanyPaid: true, bracelets: 0, braceletsPaid: true, lightman: 0, lightmanPaid: true, soundman: 0, soundmanPaid: true, singer: 1500, singerPaid: true, vatSummary: 390.24, totalPaid: 0 },
  { id: "5", event: "זאפה חיפה - 07/01/2026", status: "נכנס", tickets: 336, campaign: 5772, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 953, akomPaid: true, hallFee: 0, hallFeePaid: true, soundCompany: 0, soundCompanyPaid: true, bracelets: 2900, braceletsPaid: true, lightman: 1200, lightmanPaid: true, soundman: 1240, soundmanPaid: true, singer: 2000, singerPaid: true, vatSummary: 1276.74, totalPaid: 0 },
  { id: "6", event: "גריי תל אביב - 29/04/2026", status: null, tickets: 0, campaign: 0, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 0, akomPaid: false, hallFee: 0, hallFeePaid: false, soundCompany: 0, soundCompanyPaid: false, bracelets: 0, braceletsPaid: false, lightman: 0, lightmanPaid: false, soundman: 0, soundmanPaid: false, singer: 0, singerPaid: false, vatSummary: 0, totalPaid: 0 },
  { id: "7", event: "זאפה ירושלים - 13/05/2026", status: null, tickets: 0, campaign: 0, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 0, akomPaid: false, hallFee: 0, hallFeePaid: false, soundCompany: 0, soundCompanyPaid: false, bracelets: 0, braceletsPaid: false, lightman: 0, lightmanPaid: false, soundman: 0, soundmanPaid: false, singer: 0, singerPaid: false, vatSummary: 0, totalPaid: 0 },
  { id: "8", event: "זאפה הרצליה - 27/05/2026", status: null, tickets: 0, campaign: 0, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 0, akomPaid: false, hallFee: 0, hallFeePaid: false, soundCompany: 0, soundCompanyPaid: false, bracelets: 0, braceletsPaid: false, lightman: 0, lightmanPaid: false, soundman: 0, soundmanPaid: false, singer: 0, singerPaid: false, vatSummary: 0, totalPaid: 0 },
  { id: "9", event: "זאפה חיפה - 17/06/2026", status: null, tickets: 0, campaign: 0, refreshments: 0, design: 0, other: 0, expenseAmount: 0, paidBy: "קופה", akom: 0, akomPaid: false, hallFee: 0, hallFeePaid: false, soundCompany: 0, soundCompanyPaid: false, bracelets: 0, braceletsPaid: false, lightman: 0, lightmanPaid: false, soundman: 0, soundmanPaid: false, singer: 0, singerPaid: false, vatSummary: 0, totalPaid: 0 },
];

export const MOONLIGHT_GENERAL_EXPENSES = [
  { id: "1", date: "2025-12-28", description: "עיצוב מודעות גריי", event: "כללי", paidBy: "קופה", amount: 450, amir: 0, amirReturned: null, itamar: 0, itamarReturned: null, yuval: 0, yuvalReturned: null, fund: 450, fundReturned: "כן" },
  { id: "2", date: "2026-08-07", description: "מסך מחשב", event: "כללי", paidBy: "איתמר", amount: 400, amir: 0, amirReturned: null, itamar: 400, itamarReturned: "כן", yuval: 0, yuvalReturned: null, fund: 0, fundReturned: null },
  { id: "3", date: "2026-08-07", description: "טיפ למלצרים", event: "זאפה חיפה - 07/01/2026", paidBy: "יובל", amount: 100, amir: 0, amirReturned: null, itamar: 0, itamarReturned: null, yuval: 100, yuvalReturned: "כן", fund: 0, fundReturned: null },
  { id: "4", date: "2026-01-18", description: "מיקס ועריכת וידאו", event: "כללי", paidBy: "קופה", amount: 2500, amir: 0, amirReturned: null, itamar: 0, itamarReturned: null, yuval: 0, yuvalReturned: null, fund: 2500, fundReturned: "כן" },
];
